- name: smile
  labelleft: "Smile"
  labelright: "Frown"
  motorid: 15
  default: 0.017
  min: -1.556
  max: 1.526
  speed: 255
  acceleration: 10

- name: jaw
  labelleft: "Close jaw"
  labelright: "Open jaw"
  motorid: 17
  default: -0.838
  min: -0.838 
  max: 0.45
  speed: 200
  acceleration: 100

- name: brow
  labelleft: "Raise brow"
  labelright: "Lower brow"
  motorid: 16
  default: -0.977
  min: -1.363
  max: -0.166
  speed: 200
  acceleration: 100

- name: neck_base
  default: 0
  min: -1.57
  max: 1.57

- name: neck_pitch
  default: 0
  min: -1.57
  max: 1.57

- name: neck_roll
  labelleft: "Lean left"
  labelright: "Lean right"
  default: 0
  min: -0.6
  max: 0.6
