- name: smile
  labelleft: "Smile"
  labelright: "Frown"
  motorid: 15
  default: 0.017
  min: -1.556
  max: 1.526
  speed: 255
  acceleration: 10

- name: jaw
  labelleft: "Close jaw"
  labelright: "Open jaw"
  motorid: 17
  default: -1.271
  min: -1.271
  max: 0.017
  speed: 200
  acceleration: 100

- name: brow
  labelleft: "Raise brow"
  labelright: "Lower brow"
  motorid: 16
  default: -0.604
  min: -1.363
  max: -0.166
  speed: 200
  acceleration: 100

- name: neck_pitch
  motorid: 3
  default: 0
  min: -0.8
  max: 0.8
  speed: 200
  acceleration: 10

- name: neck_roll
  labelleft: "Lean left"
  labelright: "Lean right"
  motorid: 2
  default: 0.105
  min: -0.8
  max: 1.2
  speed: 200
  acceleration: 10

- name: neck_base
  motorid: 23
  default: 0
  min: -1
  max: 1
  speed: 255
  acceleration: 10

