- name: Neck 1
  topic: neck1
  labelleft: "Neck 1"
  labelright: ""
  default: 0
  min: -0.1
  max: 0.1

- name: Neck 2
  topic: neck2
  labelleft: "Neck 2"
  labelright: ""
  default: 0
  min: -0.1
  max: 0.1

- name: Neck 3
  topic: neck3
  labelleft: "Neck 3"
  labelright: ""
  default: 0
  min: -0.1
  max: 0.1

- name: Neck 4
  topic: neck4
  labelleft: "Neck 4"
  labelright: ""
  default: 0
  min: -0.1
  max: 0.1

- name: Neck 5
  topic: neck5
  labelleft: "Neck 5"
  labelright: ""
  default: 0
  min: -0.1
  max: 0.1

