- name: Neck 0
  topic: base
  labelleft: "Yaw"
  labelright: ""
  default: 0
  min: -3.14
  max: 3.14

- name: Neck 1
  topic: base_right
  labelleft: "Right Base Hinge"
  labelright: ""
  default: 0
  min: -0.6
  max: 0.6

- name: Neck 2
  topic: base_left
  labelleft: "Left Base Hinge"
  labelright: ""
  default: 0
  min: -0.6
  max: 0.6

- name: Neck 3
  topic: neck_right
  labelleft: "Right Neck Hinge"
  labelright: ""
  default: 0
  min: -0.6
  max: 0.6

- name: Neck 4
  topic: neck_left
  labelleft: "Left Neck Hinge"
  labelright: ""
  default: 0
  min: -0.6
  max: 0.6
