happy:
  Cheek-Squint_L: 1
  Cheek-Squint_R: 1
  Eyelid-Lower_R: 0.92593
  Eyelid-Lower_L: 0.03049
  Eyelid-Upper_R: 0.77647
  Eyelid-Upper_L: 0.40119
  Frown_R: 0.94984
  Brow-Outer_L: 0.76846
  Smile_R: 1
  Smile_L: 0.0098
  Lip-Lower_L: 0.64741
  Lip-Upper_C: 1
  Sneer_R: 0.99852
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 0.2525
  Lip-Lower_C: 1
  Brow-Inner_L: 0.7505
  Frown_L: 0.02263
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0.82235
  Brow-Outer_R: 0.35145
  EE-oo_L: 0.5
  Brow-Inner_R: 0.0246
evil:
  Cheek-Squint_L: 1
  Cheek-Squint_R: 1
  Eyelid-Lower_R: 0.92593
  Eyelid-Lower_L: 0.03049
  Eyelid-Upper_R: 1
  Eyelid-Upper_L: 0
  Frown_R: 0.94984
  Brow-Outer_L: 1
  Smile_R: 1
  Smile_L: 0.0098
  Lip-Lower_L: 0.64741
  Lip-Upper_C: 1
  Sneer_R: 0
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 0.2525
  Lip-Lower_C: 1
  Brow-Inner_L: 0
  Frown_L: 0.02263
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0
  Brow-Outer_R: 0
  EE-oo_L: 0.5
  Brow-Inner_R: 1
sad:
  Cheek-Squint_L: 0.0117
  Cheek-Squint_R: 0.10977
  Eyelid-Lower_R: 0.26797
  Eyelid-Lower_L: 0.77744
  Eyelid-Upper_R: 0.32941
  Eyelid-Upper_L: 0.79762
  Frown_R: 0
  Brow-Outer_L: 0
  Smile_R: 0
  Smile_L: 1
  Lip-Lower_L: 0.15172
  Lip-Upper_C: 0.20579
  Sneer_R: 0.99852
  Lip-Upper_L: 0.86505
  Lip-Lower_R: 0.83739
  Lip-Lower_C: 0
  Brow-Inner_L: 1
  Frown_L: 1
  EE-oo_R: 0.5
  Lip-Upper_R: 0
  Sneer_L: 0.82235
  Brow-Outer_R: 1
  EE-oo_L: 0.5
  Brow-Inner_R: 0
surprise:
  Cheek-Squint_L: 0.0117
  Cheek-Squint_R: 0.10977
  Eyelid-Lower_R: 0
  Eyelid-Lower_L: 1
  Eyelid-Upper_R: 1
  Eyelid-Upper_L: 0
  Frown_R: 0.94984
  Brow-Outer_L: 1
  Smile_R: 0
  Smile_L: 1
  Lip-Lower_L: 0.64741
  Lip-Upper_C: 1
  Sneer_R: 0.99852
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 0.2525
  Lip-Lower_C: 1
  Brow-Inner_L: 1
  Frown_L: 0.02263
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0.82235
  Brow-Outer_R: 0
  EE-oo_L: 0.5
  Brow-Inner_R: 0
angry:
  Cheek-Squint_L: 0.0117
  Cheek-Squint_R: 0.10977
  Eyelid-Lower_R: 0.92593
  Eyelid-Lower_L: 0.03049
  Eyelid-Upper_R: 0.56471
  Eyelid-Upper_L: 0.55952
  Frown_R: 0
  Brow-Outer_L: 1
  Smile_R: 0
  Smile_L: 1
  Lip-Lower_L: 0.64741
  Lip-Upper_C: 1
  Sneer_R: 0.11325
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 0.12465
  Lip-Lower_C: 0.7
  Brow-Inner_L: 0
  Frown_L: 1
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0.23529
  Brow-Outer_R: 0
  EE-oo_L: 0.5
  Brow-Inner_R: 1
afraid:
  Cheek-Squint_L: 1
  Cheek-Squint_R: 1
  Eyelid-Lower_R: 0
  Eyelid-Lower_L: 1
  Eyelid-Upper_R: 1
  Eyelid-Upper_L: 0
  Frown_R: 0
  Brow-Outer_L: 1
  Smile_R: 0
  Smile_L: 1
  Lip-Lower_L: 0.64741
  Lip-Upper_C: 1
  Sneer_R: 0.99852
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 0.2525
  Lip-Lower_C: 1
  Brow-Inner_L: 0
  Frown_L: 1
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0.82235
  Brow-Outer_R: 0
  EE-oo_L: 0.5
  Brow-Inner_R: 0.94827
disgusted:
  Cheek-Squint_L: 1
  Cheek-Squint_R: 1
  Eyelid-Lower_R: 0.92593
  Eyelid-Lower_L: 0.03049
  Eyelid-Upper_R: 0.32941
  Eyelid-Upper_L: 0.79762
  Frown_R: 0
  Brow-Outer_L: 0
  Smile_R: 0
  Smile_L: 1
  Lip-Lower_L: 0
  Lip-Upper_C: 1
  Sneer_R: 0
  Lip-Upper_L: 0.12281
  Lip-Lower_R: 1
  Lip-Lower_C: 0
  Brow-Inner_L: 0
  Frown_L: 1
  EE-oo_R: 0.5
  Lip-Upper_R: 0.92966
  Sneer_L: 0
  Brow-Outer_R: 1
  EE-oo_L: 0.5
  Brow-Inner_R: 1
