topics:
  cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base

motors:
  - name: neck_pitch_bottom
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          scale: 0.5
          translate: 0
      hardware:
        name: dynamixel
        topic: pitch1_controller/command
    min: -1
    max: 0.3

  - name: neck_pitch_top
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          scale: 0.5
          translate: 0
      hardware:
        name: dynamixel
        topic: pitch2_controller/command
    min: -0.4
    max: 0.4

  - name: neck_roll
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: x
        - name: linear
          min: -0.4
          max: 0.4
      hardware:
        name: dynamixel
        topic: roll_controller/command
    min: -0.4
    max: 0.4

  - name: neck_base
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: y
        - name: linear
          scale: -1
          translate: 0
      hardware:
        name: dynamixel
        topic: /rotate_controller/command
    min: -1.7
    max: 1.7
