topics:
  cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base

motors:
  - name: neck_pitch_bottom
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -0.5
    max: 0.5

  - name: neck_pitch_top
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -0.5
    max: 0.5

  - name: neck_roll
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: x
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -1
    max: 1

  - name: neck_base
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: y
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -1
    max: 1
