topics:
  cmd_neck_pau: neck_pitch_top;neck_pitch_bottom;neck_roll;neck_base
  cmd_eyes_pau: leye_pitch;leye_yaw;reye_pitch;reye_yaw

motors:

# ---Eyes---

  - name: leye_pitch
    binding:
      parser:
        name: getproperty
        property: m_eyeGazeLeftPitch
      function:
        - name: linear
          min: -1
          max: 1
      hardware:
        name: pololu
        id: -1
        speed: 200
        acceleration: 100
    min: -1
    max: 1

  - name: leye_yaw
    binding:
      parser:
        name: getproperty
        property: m_eyeGazeLeftYaw
      function:
        - name: linear
          min: -1
          max: 1
      hardware:
        name: pololu
        id: -1
        speed: 200
        acceleration: 100
    min: -1
    max: 1

  - name: reye_pitch
    binding:
      parser:
        name: getproperty
        property: m_eyeGazeRightPitch
      function:
        - name: linear
          min: -1
          max: 1
      hardware:
        name: pololu
        id: -1
        speed: 200
        acceleration: 100
    min: -1
    max: 1

  - name: reye_yaw
    binding:
      parser:
        name: getproperty
        property: m_eyeGazeRightYaw
      function:
        - name: linear
          min: -1
          max: 1
      hardware:
        name: pololu
        id: -1
        speed: 200
        acceleration: 100
    min: -1
    max: 1

# ---Neck---

  - name: neck_pitch_bottom
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -0.5
    max: 0.5

  - name: neck_pitch_top
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: z
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -0.5
    max: 0.5

  - name: neck_roll
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: x
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -1
    max: 1

  - name: neck_base
    binding:
      parser:
        name: getproperty
        property: m_headRotation
      function:
        - name: quaternion2euler
          axis: y
        - name: linear
          min: -1
          max: 1
      hardware:
        name: dynamixel
        topic: (not set)
    min: -1
    max: 1
