- name: smile
  motorid: 15
  default: 0.017
  min: -1.556
  max: 1.526
  speed: 30
  acceleration: 10

- name: jaw
  motorid: 17
  default: -0.838
  min: -0.838
  max: 0.45
  speed: 30
  acceleration: 100

- name: brow
  motorid: 16
  default: -0.977
  min: -1.363
  max: -0.166
  speed: 30
  acceleration: 100