#All values are in coefficients (0..1 being proportional to min..max)
happy:
  smile: 0
  jaw: 0.567
  brow: 0

sad:
  smile: 1
  jaw: 0
  brow: 0.366

surprised:
  smile: 0
  jaw: 0
  brow: 1

evil:
  smile: 0
  jaw: 0
  brow: 1

afraid:
  smile: 1
  jaw: 0
  brow: 0

horrified:
  smile: 1
  jaw: 0.661
  brow: 0

annoyed:
  smile: 1
  jaw: 0
  brow: 1

innocent:
  smile: 0
  jaw: 0
  brow: 0

violent:
  smile: 1
  jaw: 1
  brow: 1

eureka:
  smile: 0.126
  jaw: 1
  brow: 0