- name: jaw
  enabled: true
  motorid: 17
  binding:
    parser: fsshapekey
    function: linear
    args:
      shapekey: JawOpen
      min: 0
      max: 1
  min: -0.838
  max: 0.45
  speed: 200
  acceleration: 100

- name: brow
  enabled: true
  motorid: 16
  binding:
    parser: fsshapekey
    function: linear
    args:
      shapekey: BrowsD_L
      min: 0.413
      max: 1
  min: -1.55
  max: -0.2
  speed: 200
  acceleration: 100

- name: smile
  enabled: true
  motorid: 15
  binding:
    parser: fsshapekey
    function: weightedsum
    args:
      shapekey: MouthSmile_L;MouthSmile_R;MouthFrown_L;MouthFrown_R
      imin: 0.5
      terms:
        - {min: 0, max: 1, imax: 0.25}
        - {min: 0, max: 1, imax: 0.25}
        - {min: 0, max: 1, imax: 0.75}
        - {min: 0, max: 1, imax: 0.75}
  min: -1.55
  max: 1.55
  speed: 255
  acceleration: 10

- name: neck_pitch
  enabled: true
  motorid: 3
  binding:
    parser: getproperty
    function: linear
    args:
      property: m_headRotation:x
      min: 0.25
      max: 0
  min: 0
  max: 0.5
  speed: 200
  acceleration: 10

- name: neck_roll
  enabled: true
  motorid: 2
  binding:
    parser: getproperty
    function: linear
    args:
      property: m_headRotation:z
      min: 0
      max: -0.25
  min: 0
  max: 0.5
  speed: 200
  acceleration: 10

- name: neck_base
  enabled: true
  motorid: 23
  binding:
    parser: getproperty
    function: linear
    args:
      property: m_headRotation:y
      min: 0
      max: 0.5
  min: 0
  max: 0.5
  speed: 255
  acceleration: 10
