- {default: 0, labelleft: Yaw, labelright: '', max: 3.14, min: -3.14, name: Neck 0,
  topic: neck0}
- {default: 0, labelleft: Left Base Hinge, labelright: '', max: 0.6, min: -0.6, name: Neck
    2, topic: neck2}
- {default: 0, labelleft: Right Neck Hinge, labelright: '', max: 0.6, min: -0.6, name: Neck
    3, topic: neck3}
- {default: 0, labelleft: Right Base Hinge, labelright: '', max: 0.6, min: -0.6, name: Neck
    1, topic: neck1}
- {default: 0, labelleft: Left Neck Hinge, labelright: '', max: 0.6, min: -0.6, name: Neck
    4, topic: neck4}
- {default: 0.153, labelleft: Eyes_Pitch, labelright: null, max: 0.705, min: -0.596,
  motor_id: 17, name: Eyes_Pitch, topic: right}
- {default: 0.188, labelleft: Eye_L, labelright: null, max: 0.57, min: -0.262, motor_id: 0,
  name: Eye_L, topic: /fritz/left/command}
- {default: -0.063, labelleft: Eye_R, labelright: null, max: 0.26, min: -0.399, motor_id: 0,
  name: Eye_R, topic: /fritz/right/command}
