pau2motors:
    topics:
      cmd_face_pau: jaw;brow;smile
      cmd_neck_pau: neck_pitch;neck_roll;neck_base

    motors:
      jaw:
        binding:
          parser:
            name: fsshapekey
            shapekey: JawOpen;LipsLowerOpen;LipsLowerDown
          function:
            name: weightedsum
            imin: 0
            terms:
              - {min: 0, max: 0.8, imax: 1}
              - {min: 0, max: 1, imax: 0.2}
              - {min: 0, max: 1, imax: 0.4}
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 5
            speed: 200
            acceleration: 100
        min: -0.546
        max: 0.9

      brow:
        binding:
          parser:
            name: fsshapekey
            shapekey: BrowsD_L;BrowsD_R;BrowsU_C
          function:
            name: weightedsum
            imin: 0.5
            terms:
              #(D_L, D_R, U_C) = (1, 1, 1) is the saddest brow possible,
              #(D_L, D_R, U_C) = (1, 1, 0) is an angry brow,
              #(D_L, D_R, U_C) = (0, 0, 1) is a high (happy, surprised) brow.
              - {min: 0.413, max: 1, imax: 0.75}
              - {min: 0.413, max: 1, imax: 0.75}
              - {min: 0, max: 1, imax: 0}
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 3
            speed: 200
            acceleration: 100
        min: -1.36
        max: -0.166
        # New limits, when Einstein wasn't able to raise brow, only lower
        #min: -1.0
        #max: -0.2

      smile:
        binding:
          parser:
            name: fsshapekey
            shapekey: MouthSmile_L;MouthSmile_R;MouthFrown_L;MouthFrown_R;JawOpen
          function:
            name: weightedsum
            imin: 0.5
            terms:
              - {min: 0, max: 1, imax: 0.25}
              - {min: 0, max: 1, imax: 0.25}
              - {min: 0, max: 1, imax: 0.75}
              - {min: 0, max: 1, imax: 0.75}
              #Hold back on the smile when jaw is widely opened.
              - {min: 0.6, max: 0.8, imax: 0.7}
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 4
            speed: 200
            acceleration: 100
        min: -1.55
        max: 1.55

      neck_pitch:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: z
            - name: linear
              min: 0.8
              max: -0.8
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 2
            speed: 100
            acceleration: 10
        min: -0.4
        max: 1.2

      neck_roll:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: x
            - name: linear
              min: 0.6
              max: -0.6
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 1
            speed: 100
            acceleration: 10
        min: -0.85
        max: 0.35

      neck_base:
        binding:
          parser:
            name: getproperty
            property: m_headRotation
          function:
            - name: quaternion2euler
              axis: y
            - name: linear
              min: 1
              max: -1
          hardware:
            name: pololu
            topic: pololu/cmd_pololu
            id: 0
            speed: 100
            acceleration: 10
        min: -1.9752
        max: 0.0248
