# Eye tracking
eye_tracking:
    angles:
        w: 40 # Angle (deg) which will be proportional to full height of image from camera feed and added to PAU
        h: 60 # Angle (deg) which will be proportional to full width of image from camera feed and added to PAU
    center: # relative camera image point which represents point where eyeball is looking at
        w: 0.5
        h: 0.5
    distance-max: 0.2 # Relative distance from camera image center to face target in which face considered to be same.
